using Microsoft.EntityFrameworkCore;
using Domain.Entities;

namespace Infrastructure.Data
{
    /// <summary>
    /// Application Database Context
    /// 
    /// This is Entity Framework Core's connection to the database.
    /// It maps domain entities to database tables.
    /// 
    /// Every DbSet represents a table in the database:
    /// - DbSet<Product> Products → "Products" table
    /// 
    /// Entity Framework uses this class to:
    /// 1. Create database migrations
    /// 2. Execute queries
    /// 3. Track changes to entities
    /// 4. Manage transactions
    /// </summary>
    public class ApplicationDbContext : DbContext
    {
        /// <summary>
        /// Constructor - receives options from dependency injection
        /// 
        /// Program.cs configures these options:
        /// - Which database (SQL Server, PostgreSQL, etc.)
        /// - Connection string
        /// - Other DbContext settings
        /// </summary>
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        // DATABASE TABLES
        // Each DbSet maps to a table in the database
        // Entity Framework automatically creates these from domain entities

        /// <summary>
        /// Products table - contains all products in the system
        /// </summary>
        public DbSet<Product> Products { get; set; } = null!;

        /// <summary>
        /// Users table - contains all users in the system
        /// </summary>
        public DbSet<User> Users { get; set; } = null!;

        // Add more DbSets here as you add more domain entities
        // Example:
        // public DbSet<Order> Orders { get; set; }
        // public DbSet<Customer> Customers { get; set; }

        /// <summary>
        /// Optional: Configure entity mappings and relationships
        /// 
        /// This method is called when the model is being created.
        /// Use it to configure:
        /// - Table names
        /// - Column properties
        /// - Relationships between entities
        /// - Constraints and validations
        /// </summary>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // ✅ IMPORTANT: All required fields must have static values in HasData
            // Missing fields cause "PendingModelChangesWarning" because EF applies
            // defaults at different times, making the model appear "changed"

            // 🔐 SEED USER CREDENTIALS (for development/testing only):
            // Username: admin01
            // Email: admin@gmail.com
            // Password: password123
            // Hash generated by BCrypt with work factor 12
            string passwordHash = "$2a$12$w/uSw0m7daZZnQRy/7vs9upf/k6TXPGv3K.avLrn0jfjyaXd.5pj2";

            modelBuilder.Entity<User>().HasData(new User
            {
                Id = 1,
                Username = "admin01",
                Email = "admin@gmail.com",
                PasswordHash = passwordHash,
                FirstName = "Admin",
                LastName = "User",
                Role = "Admin",
                CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                IsActive = true,
                RefreshToken = null,
                RefreshTokenExpiryTime = null
            });

            // ✅ IMPORTANT: Use static DateTime, NOT DateTime.UtcNow
            // DateTime.UtcNow changes every build, causing migration warnings
            modelBuilder.Entity<Product>().HasData(new Product
            {
                Id = 1,
                Name = "Sample Product",
                Description = "This is a sample product.",
                Price = 30,
                Stock = 100,
                CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                UpdatedAt = null
            });

            // EXAMPLE: Configure Product entity
            // Uncomment and modify as needed
            modelBuilder.Entity<Product>(entity =>
            {
                // Table name in database
                entity.ToTable("Products");

                // Primary key
                entity.HasKey(e => e.Id);

                // Column configurations
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.Description)
                    .HasMaxLength(1000);

                entity.Property(e => e.Price)
                    .HasPrecision(18, 2); // decimal(18,2)

                // Indexes
                entity.HasIndex(e => e.Name)
                    .IsUnique(false)
                    .HasDatabaseName("idx_product_name");
            });

            modelBuilder.Entity<User>(entity =>
            {
                // Table name
                entity.ToTable("Users");

                // Primary key
                entity.HasKey(u => u.Id);

                // Username: Required, unique, max 50 chars
                entity.Property(u => u.Username)
                    .IsRequired()
                    .HasMaxLength(50);
                entity.HasIndex(u => u.Username)
                    .IsUnique();

                // Email: Required, unique, max 100 chars
                entity.Property(u => u.Email)
                    .IsRequired()
                    .HasMaxLength(100);
                entity.HasIndex(u => u.Email)
                    .IsUnique();

                // Password hash: Required (stores BCrypt hash)
                entity.Property(u => u.PasswordHash)
                    .IsRequired()
                    .HasMaxLength(200);
             
                // First name: Required, max 50 chars
                entity.Property(u => u.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                // Last name: Required, max 50 chars
                entity.Property(u => u.LastName)
                .IsRequired()
                .HasMaxLength(50);

                // Role: Required, max 20 chars, default "User"
                entity.Property(u => u.Role)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasDefaultValue("User");

                // Refresh token: Optional, max 200 chars
                entity.Property(u => u.RefreshToken)
                    .HasMaxLength(200);

                // Created at: Default to current UTC time
                entity.Property(u => u.CreatedAt)
                    .HasDefaultValueSql("GETUTCDATE()");

                // Is active: Default to true
                entity.Property(u => u.IsActive)
                    .HasDefaultValue(true);
            });
        }
    }
}